### ISSUE TITLE
Api is down

### ISSUE THREAD

**Issue by dmacbeath** [sameerkumar18/useless-facts-api#1]
Hey, there is this error when you go to the api now 

''An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command''

**Comment by sameerkumar18** [comment]
Thanks for reporting this @dmacbeath 
The API should be working now

**Comment by elegantShock2258** [comment]
@sameerkumar18  the api still isn't working!

**Comment by sameerkumar18** [comment]
Hi @oliverBrotherhood3307 Some error on Heroku/Cloudflare's end. Looking into this

**Comment by sameerkumar18** [comment]
It's back live now @oliverBrotherhood3307
